const jobsAT = [
  {country:'AT', title:'Senior Project Engineer Robotics (m/w/d)', company:'KUKA GmbH', location:'Steyregg', kuka:'employer', match:'extended', focus:'Kundenanforderungen, Machbarkeit, Lösungskonzepte und Steuerung von Robotics-Projekten.', conditions:'Vollzeit · Homeoffice · ab 4.500 € brutto/Monat', freshness:'karriere.at · vor 4 Tagen', url:'https://www.karriere.at/jobs/7816535'},
  {country:'AT', title:'Roboter-Simulationsingenieur und Offline Programmierer (w/m/d)', company:'TMS Turnkey Manufacturing Solutions GmbH', location:'Linz', kuka:'yes', match:'direct', focus:'Robotersimulation und digitaler Zwilling für KUKA, FANUC, ABB; Process Simulate/DELMIA.', conditions:'Vollzeit · Homeoffice · ca. 10 % Reisen · ab 47.544 €/Jahr', freshness:'karriere.at · vor 5 Tagen', url:'https://www.karriere.at/jobs/7841900'},
  {country:'AT', title:'Softwareengineering SPS m/w/x', company:'Wintersteiger Holding AG', location:'Mettmach', kuka:'yes', match:'direct', focus:'SPS- und Roboterprogrammierung, Prozess-Tests, Inbetriebnahme und Support; ABB/KUKA/FANUC.', conditions:'Vollzeit · Homeoffice · ca. 20 % Reisen', freshness:'karriere.at · heute veröffentlicht', url:'https://www.karriere.at/jobs/7803704'},
  {country:'AT', title:'Software Entwickler:in – individuelle Roboterprogrammierung', company:'ETEC Automatisierungstechnik Ges.m.b.H.', location:'Stans, Tirol', kuka:'partner', match:'direct', focus:'Entwicklung maßgeschneiderter Software, individuelle Roboterprogrammierung und Funktionsprüfung an Sondermaschinen.', conditions:'Vollzeit · direkte Bewerbung über das Talent Board', freshness:'Arbeitgeber direkt · geprüft 16.07.2026', url:'https://www.etec.tirol/unternehmen/talent-board/entwicklung-konstruktion'},
  {country:'AT', title:'Senior-Automatisierungs-/Servicetechniker – Schwerpunkt Robotik (m/w/d)', company:'HEITEC Systemtechnik Österreich', location:'Ardagger Stift', kuka:'partner_explicit', match:'direct', focus:'Entwicklung und Optimierung von SPS- und Roboterprogrammen sowie Inbetriebnahme von Industrierobotern; KUKA und FANUC ausdrücklich genannt.', conditions:'Vollzeit · Reisetätigkeit · bis 68.000 € brutto/Jahr', freshness:'Arbeitgeber direkt · geprüft 16.07.2026', url:'https://www.heitec.de/karriere/stellenangebote/detail/senior-automatisierungs-servicetechniker-im-sondermaschinenbau-schwerpunkt-robotik-mwd'},
  {country:'AT', title:'Steuerungstechniker (m/w/d)', company:'FREY Automation GmbH', location:'Lienz', kuka:'partner', match:'extended', focus:'Softwareentwicklung und SPS-Programmierung mit Beckhoff und Siemens; Grundkenntnisse in der Robotik.', conditions:'Vollzeit · flexible Arbeitszeit · Überzahlung möglich', freshness:'Arbeitgeber direkt · geprüft 16.07.2026', url:'https://www.frey-automation.at/freye-stellen'},
  {country:'AT', title:'HTL-Absolvent – Automatisierungstechnik / Roboterprogrammierer (m/w/d)', company:'SPS Technik GmbH', location:'St. Valentin', kuka:'partner', match:'direct', focus:'Programmierung von Sondermaschinen und komplexen Roboterapplikationen sowie internationale Inbetriebnahmen.', conditions:'Vollzeit · Reisetätigkeit · ab 40.600 € brutto/Jahr', freshness:'Arbeitgeber direkt · geprüft 16.07.2026', url:'https://www.sps.at/de/karriere-jobs/'},
  {country:'AT', title:'Robotics Commissioning Engineer (m/w/d)', company:'KNAPP', location:'Hart bei Graz', kuka:'no', match:'direct', focus:'Software- und Steuerungsinbetriebnahme für robotergestützte Systeme sowie Tests und Fehleranalyse.', conditions:'Vollzeit · ca. 50 % internationale Reisen · ab 3.040 €/Monat', freshness:'karriere.at · aktiv geprüft', url:'https://www.karriere.at/jobs/7780577'},
  {country:'AT', title:'Robotics Integration Engineer – Humanoide Robotik (w/m/x)', company:'DCCS GmbH', location:'Graz / Wels', kuka:'no', match:'direct', focus:'Programmierung von Roboterplattformen, Bewegungsbahnen, Greifen und Integration mit ROS 2.', conditions:'Vollzeit · Hybrid · ab 5.444 €/Monat', freshness:'karriere.at · aktiv geprüft', url:'https://www.karriere.at/jobs/10024361'},
  {country:'AT', title:'ApplikationsentwicklerIn für mobile Robotik (m/w/x)', company:'DS Automotion GmbH', location:'Linz', kuka:'no', match:'direct', focus:'C++/Linux-Applikationen für AGV/AMR, Sensorik, Fahrzeugtests und Inbetriebnahme beim Kunden.', conditions:'Vollzeit · Homeoffice · mind. 20 % Reisen · ab 3.500 €/Monat', freshness:'karriere.at · aktuell', url:'https://www.karriere.at/jobs/7823477'},
  {country:'AT', title:'Applikationsentwickler C++ / Mobile Robotik (m/w/d)', company:'FERCHAU Austria GmbH', location:'Linz', kuka:'no', match:'direct', focus:'Integration autonomer Transportfahrzeuge, C++/Linux, Sensorik, Tests und Kundeninbetriebnahme.', conditions:'Vollzeit · vor Ort · ca. 20 % Reisen · 49.000–70.000 €/Jahr', freshness:'karriere.at · 06.07.2026', url:'https://www.karriere.at/jobs/7838270'},
];
